//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visitas
    {
        public int ID { get; set; }
        public string Motivo_visita { get; set; }
        public string Fecha_visita { get; set; }
        public string Hora_entrada { get; set; }
        public string Hora_salida { get; set; }
        public string Nombre_completo { get; set; }
        public int Contacto_que_lo_recibio { get; set; }
    
        public virtual Contacto Contacto { get; set; }
    }
}
